### ISSUE TITLE
"Cancer Germline Variants" container overgrowth

### ISSUE THREAD

**Issue by Yiran-Guo** [d3b-center/OMPARE#7]
I found a trivial issue of the report. When I scroll down the `Cancer Germline Variants`, it masks the first line of `Genomic Summary`.
Also when I scroll to the right of the `Cancer Germline Variants`, the header line masks the first line of `Disease Specific information` too.
![image](https://user-images.githubusercontent.com/5854272/78707609-d3d13f00-78de-11ea-9576-e44e23c4f8a0.png)
![image](https://user-images.githubusercontent.com/5854272/78707620-d92e8980-78de-11ea-873d-9a7fd686afd5.png)
![image](https://user-images.githubusercontent.com/5854272/78707632-de8bd400-78de-11ea-9dee-586d085a870d.png)

**Comment by komalsrathi** [comment]
@Yiran-Guo This looks like a bug with `flexboard + kable`. Looking into this, will let you know if I can figure it out.
