### ISSUE TITLE
Verify processing pipelines for TCGA vs PBTA

### ISSUE THREAD

**Issue by aadamk** [d3b-center/OMPARE#8]
Per discussion today, we need to clarify the process for determining mutational burden in PBTA vs adult TCGA samples as reported in the clinical reports (below).

Per the ```tmbProfile.R``` code, are the mutect2 outputs for both adult and pediatric cohorts the result of the same filtering steps within GATK?    

![image](https://user-images.githubusercontent.com/20973091/78715164-fcf7cc80-78ea-11ea-913c-e478afc27a6a.png)

**Comment by komalsrathi** [comment]
@aadamk In tmbProfile, this is what I am doing: 

Reading in current patient's mutect2 results: https://github.com/d3b-center/OMPARE/blob/master/code/tmbProfile.R#L8-L17

Filtering to nonsense and missense: https://github.com/d3b-center/OMPARE/blob/master/code/tmbProfile.R#L19

Intersecting with bed file (generated by @tkoganti): https://github.com/d3b-center/OMPARE/blob/master/code/tmbProfile.R#L24

Reading PBTA and TCGA data (generated by @tkoganti): https://github.com/d3b-center/OMPARE/blob/master/code/tmbProfile.R#L35

So, for each patient, the _PBTA data, TCGA data and bed file_ remain the same, the only difference is the patient-specific mutect2 result which is used to calculate the number of missense+nonsense overlapping with the bed file, which is then used to divide by the TMB which is also hardcoded to 77.46 MB (77462866 size of the bed file). 

I think @tkoganti may be the point person if you have questions regarding the [**bed**](https://github.com/d3b-center/OMPARE/blob/master/data/Reference/xgen-exome-research-panel-targets_hg38_ucsc_liftover.100bp_padded.sort.merged.bed), [**PBTA**](https://github.com/d3b-center/OMPARE/blob/master/data/Reference/pbta-TMBscores_withdiseastype.txt) and [**TCGA**](https://github.com/d3b-center/OMPARE/blob/master/data/Reference/TCGA_diseasetypes_and_samples_TMBscores.txt)

**Comment by tkoganti** [comment]
Hi @komalsrathi and @aadamk - here is the ticket that shows what data was used - https://github.com/d3b-center/bixu-tracker/issues/444

Here is the mutect2 file used from PBTA - https://cavatica.sbgenomics.com/u/cavatica/pbta/files/5e160112e4b09d9aaf473d8b/

Here is the BED file I was using - https://cavatica.sbgenomics.com/u/kfdrc-harmonization/sd-8y99qzjj/files/5dfbe088e4b09d9aaf41d45a/

**Comment by tkoganti** [comment]
Also to clarify about the disease types, we were using `short_histology` column from [pbta-histologies.tsv](https://cavatica.sbgenomics.com/u/cavatica/pbta/files/5dfb98aae4b054952cd2c330/)

**Comment by aadamk** [comment]
Thanks @tkoganti and @komalsrathi. Closing this issue.
