### ISSUE TITLE
xCell and GSEA for genomically similar patients to PNOC008-13

### ISSUE THREAD

**Issue by aadamk** [d3b-center/OMPARE#9]
@komalsrathi 
For the current PNOC008-13, the genomically similar patients constitute PBTA HGGs based on pearson correlation coefficients of expression profiles, right? 

For the 15 similar patients, the following would be essential for the 4/10 meeting:
1) Immune profile from xCell pipeline as a basis of comparison to patient 13.
2) GSEA analysis and resulting pathway bar plots to compare to patient 13.

For 1, is the output ```.Rdata``` file below the result of the same pipeline you use for the PNOC008 clinical reports? 

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/immune-deconv/results/deconv-output.RData

For 2), do the output GSEA files contain scores resulting from the same pipeline+calculations as the scores included in the clinical report?

https://github.com/AlexsLemonade/OpenPBTA-analysis/blob/master/analyses/gene-set-enrichment-analysis/results/gsva_scores_polya.tsv

**Comment by komalsrathi** [comment]
I will try but cannot guarantee as this is extremely short notice

**Comment by komalsrathi** [comment]
Just to give more context before our meeting today:  

- Based on yesterday's discussion,  I have changed the genomically similar to top 20 **any PBTA histology + all previous PNOC008 patients (not restricted to HGG)**. The table of `Genomically Similar Patients` will now show the correlation value as well.

- Same goes for the KM Plot - which now uses top 20 samples (any histologies from PBTA and GBM from TCGA) that are most correlated with the patient and have associated survival data. Ofcourse, here we won't have the previous PNOC008 patients.

- Currenly, Immuneprofile uses xCell from entire PBTA expression data (not just HGG and not just most correlated samples). Would you want another Immuneprofile plot using xCell for just PNOC008 patients?

- Currently, for pathway enrichment, I am using this script https://github.com/d3b-center/OMPARE/blob/master/code/tabulate_excel.R to do comparisons of which pathways are up and down in the patient of interest vs GTEx/PBTA HGG and PBTA full dataset. I report these for each patient in an excel file which is under the reports folder on cavatica. What I was thinking is, pulling all those results from prior patients (where this report was generate) and counting which pathways are up and down in the most correlated patients. So, a table of pathway and number of times it is seen Up/Down in most correlated patients.

**Comment by komalsrathi** [comment]
Send these by end of business:

* Additional Immuneprofile: Top 20 genomically similar (PNOC008 + PBTA)
* Common pathways for genomically similar patients (PNOC008)

**Comment by aadamk** [comment]
Closing this issue as the above are complete.
